[package]
name = "include2dot"
version = "0.1.0"
authors = ["Ky Waegel <kwaegel@users.noreply.github.com>"]

[dependencies]
regex = "0.*"
lazy_static = "0.*"
petgraph = "0.*"
walkdir = "1.*"
itertools = "0.*"

[dependencies.clap]
version = "2.*"
default-features = false