[package]
name = "include2dot"
version = "0.1.0"
authors = ["Ky Waegel <kwaegel@users.noreply.github.com>"]

[dependencies]
regex = "0.1"
lazy_static = "0.2"
petgraph = "0.4"
walkdir = "0.1"

[dependencies.clap]
version = "2"
default-features = false